local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: false
  
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  plugins:
   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    inflation_radius: 1.75
    cost_scaling_factor: 2.58

  obstacle_layer:
    observation_sources: laser
    laser: {sensor_frame: laser, topic: scan, data_type: LaserScan, expected_update_rate: 0.0, observation_persistence: 0.0, marking: true, clearing: true,  min_obstacle_height: 0.0, max_obstacle_height: 0.90}    
    
     
