global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 5.0
  static_map: true #false
#  inflation_radius: 0.5
  plugins:
   - {name: static_layer, type: "costmap_2d::StaticLayer"}
#   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

#  inflation_layer:
#   inflation_radius: 1.5
#   cost_scaling_factor: 15.0

#  obstacle_layer:
#    observation_sources: laser
#    laser: {sensor_frame: hl_laser, topic: hopel_scan, data_type: LaserScan, expected_update_rate: 0.0, observation_persistence: 0.0, marking: true, clearing: true,  min_obstacle_height: 0.0, max_obstacle_height: 0.90, obstacle_range: 0.5}
