base_global_planner: "navfn/NavfnROS"
base_local_planner: "dwa_local_planner/DWAPlannerROS"

planner_patience: 2.0
#planner_frequency: 1.0
shutdown_costmaps: false

#controller_patience: 5
#oscillation_timeout: 2.0
controller_frequency: 5.0 #3.0
recovery_behaviour_enabled: true
clearing_rotation_allowed: true
