DWAPlannerROS:
  # acc_lim_x: 0.5
  acc_lim_x: 2.0 #0.7
  acc_lim_y: 0.0
  acc_lim_th: 2.0
# max_trans_vel: 0.7
# max_trans_vel: 0.5 #1.4
# min_trans_vel: -0.05
# max_vel_x: 0.7
  max_vel_x: 1.0 #1.4
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 1.0
  min_rot_vel: 0.40

  yaw_goal_tolerance: 0.20 #0.35
  xy_goal_tolerance: 0.20 #0.35
  latch_xy_goal_tolerance: true

  sim_time: 1.7
  sim_granularity: 0.025
  vx_samples: 4
  vtheta_samples: 10

