axis_linear: 1 # Left stick Up/Down
scale_linear: 0.3
scale_linear_turbo: 0.7

axis_angular: 2 # Right stick Left/Right
scale_angular: 0.4
scale_angular_turbo: 1.0

enable_button: 8 # L2 trigger
enable_turbo_button: 9 # L1 button